name: isolate_issue
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  functions_framework: ^0.4.0
  http: ^1.2.2
  shelf: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
